### ISSUE TITLE
[FEATURE] Make multi-touch events possible

### ISSUE THREAD

**Issue by mmakaay** [mmakaay/esphome-xiaomi_bslamp2#14]
**Is your feature request related to a problem? Please describe.**
It currently is only possible to detect single-touch events using the binary_sensor implementation. The front panel event system provides enough information to handle multi-touch events as well. It would be really nice to expose these.

The original firmware uses a multi-touch option too. Holding the power and color buttons for a while will reset the device. The original device being able to detect multi-touch events is another good reason to implement this ;-)

**Describe the solution you'd like**

Currently, the `part` property can be used to define what part of the front panel to react to.
I propose adding a `parts` property that does the same thing, but that accepts multiple part names.
This would look like:

```yaml
binary_sensor:
  - platform: xiaomi_bslamp2
    parts:
      - power button
      - color_button
```
