### ISSUE TITLE
[FEATURE] Make the repository compatible with the upcoming external_components feature

### ISSUE THREAD

**Issue by mmakaay** [mmakaay/esphome-xiaomi_bslamp2#16]
The ESPHome team is working on a great option to work with components that are hosted on GitHub.
This makes it very easy to use third party components, without all the hassle of downloading the code, and manually moving it to the correct directories on the build system. For example the Bedside Lamp 2 code could be included in the build by adding something like this to the yaml config:

```yaml
external_components:
  - source:
      type: git
      url: https://github.com/mmakaay/esphome-xiaomi_bslamp2
      ref: 1.0.0-RC1
```

To make this work, the repository needs to be structured in a standard way.
Because of the big jump in usability, I will happily make my repo compatible with the requirements.

The change is not very complicated:

* Create a directory `components/xiaomi_bslamp2`
* Move all code that is required for the component to work into that new directory

I will do this, before going to a first stable release of the code.
