### ISSUE TITLE
[BUG] Issue with external_components in example.yaml

### ISSUE THREAD

**Issue by maartenpaul** [mmakaay/esphome-xiaomi_bslamp2#54]
I tried today to compile firmware using example.yaml on this github. It returned an error using the ESPHome dashboard:
``` 
[refresh] is an invalid option for [source]. Did you mean [ref]?
refresh: 60s [source /home/maarten/config/example.yaml:118]
```

I'm not an expert in Esphome, but changing the indentation of `refresh: 60s` seems to have solved the problem and I have successfully flashed my bslamp2.

```yaml
external_components:
  - source:
      type: git
      url: https://github.com/mmakaay/esphome-xiaomi_bslamp2
      ref: main
    refresh: 60s
```

As I'm not sure this is the correct solution I leave it here as a bug.
