### ISSUE TITLE
[FEATURE] Implement presets support

### ISSUE THREAD

**Issue by mmakaay** [mmakaay/esphome-xiaomi_bslamp2#8]
**Is your feature request related to a problem? Please describe.**
When using the original firmware for the Bedside Lamp 2, one can configure two sets of preset light colors: one for RGB light, and one for white color-temperature-based light. Using the color button, one can switch between these two sets (long press) and between the presets within such set (short press).

It would be awesome provide easy to use support for this.

**Describe the solution you'd like**

* Add a `presets` configuration option for the light.
* This option can have one or more (optionally) named sets of presets (no need to hard-code it to two!).
* Each set can contain one or more (optionally) named presets.
* A preset can contain any light setting (no need to group them by light mode like the original does).

Services are exposed to allow switching to a specific set, the next set, a specific preset or the next preset.

With these in place, we have a very flexible manner to re-implement the original behavior, as well as new behaviors.

**Describe alternatives you've considered**
I've looked for some sort of scenes support within the ESPHome context, but haven't found it.
Even if scene support does exist, we still need a data structure for handling the "sets of presets" setup.
We could let a preset reference  a scene in such case though, to reuse its functionality.

Another way that one could handle things, is by not making the lamp smarter, but by offloading the scene knowledge to Home Assistant. The lamp configuration could fire some events in response to touch events for the color button, and Home Assistant could pick up on these by setting the scene for the lamp.
This is a good alternative, but I think that it might become a bit cumbersome to implement a behavior that looks like the original behavior in such way.

**Comment by mmakaay** [comment]
Let's do some wishful programming: start with the config declaration and work back from there. I think this would be a really nice way to register some groups of presets:

```yaml
light:
  - platform: xiaomi_bslamp2
    presets:
      - rgb:
          - red_bright: { red: 1 }
          - green: { green: 1 }
          - blue_dimmed: { blue: 1 }
          - yellow: { red: 1, green: 1 }
          - something: { red: 0.2, green: 0.4, blue: 1 }
      - white:
          - warm: { color_temperature: 588 }
          - luke: { color_temperature: 400 }
          - chilly: { color_temperature: 275 }
          - cold: { color_temperature: 153 }
```

All a preset needs are `red`, `green`, `blue` and `color_temperature`. It would not be hard to support `brightness` too, but if I think ahead to how that would work out when using it, it doesn't feel "right'. The brightness is a separate thing for me, and I would like the color button to modify just that: the light's color.

*Of course, when people really need brightness as a preset property, then please let me know.*

**Comment by mmakaay** [comment]
I started the implementation in a side-branch: https://github.com/mmakaay/esphome-xiaomi_bslamp2/tree/add-support-for-presets

The implementation for the presets configuration is ready. The yaml can be processed and C++ code is generated to fill a store with the configured presets. For each preset, a `LightCall` object is generated, which should make it really easy to activate a given preset.

Now some options are needed to activate a specific group or preset within a group.
And also some options for switching to the next group or next preset within a group.

Tomorrow I'll think about the exact format for the required action(s), and then implement them..

**Comment by mmakaay** [comment]
Two automation acions were implemented for switching between configured presets.
These can be used to emulate the behavior of the original device firmware:

Here are the relevant bits of configuration that are involved in getting the color button to operate like the original one:

```yaml
light:
  - platform: xiaomi_bslamp2
    presets:
      RGB:
        red:         { red: 100% }
        green:       { green: 100% }
        blue:        { blue: 100% }
        yellow:      { red: 100%, green: 100% }
        purple:      { red: 100%, blue: 100% }
      white:
        cold:        { color_temperature: 153 }
        CHILLY:      { color_temperature: 275 }
        luke:        { color_temperature: 400 }
        # bug? 588 shows error about white not being valid
        WARM:        { color_temperature: 587 }

binary_sensor:
  - platform: xiaomi_bslamp2
    id: ${id_color_button}
    part: color button
    on_multi_click:
      - timing:
          - ON for at most 0.6s
        then:
          - preset.activate:
              next: preset
      - timing:
          - ON for at least 0.6s
        then:
          - preset.activate:
              next: group
```

**Comment by mmakaay** [comment]
New actions have been implemented, which make it possible to activate a preset group or a specific preset. This completes the list of actions that seemed useful to me. Available actions are now:

```yaml
preset.activate:
    next: group

preset.activate:
    next: preset

preset_activate:
    group: some_group_name

preset_activate:
    group: some_group_name
    preset: some_preset_name
```

Also implemented is a way to specify the target for `preset.activate` as a simple string.
Using these, the above actions can be written as follows:

```yaml
preset_activate: next_group

preset_activate: next_preset

preset_activate: some_group_name

preset_activate: some_group_name.some_preset_name
```
